// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBlogApp.Models;

#nullable disable

namespace PersonalBlogApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240530100639_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PersonalBlogApp.Models.Writing", b =>
                {
                    b.Property<int>("WritingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WritingDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WritingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WritingId");

                    b.ToTable("Writings");
                });
#pragma warning restore 612, 618
        }
    }
}
