// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace PersonalBlogApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Framework"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Markup Language"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Design Helper"
                        });
                });

            modelBuilder.Entity("Entities.Models.Writing", b =>
                {
                    b.Property<int>("WritingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WritingDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WritingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WritingId");

                    b.ToTable("Writings");

                    b.HasData(
                        new
                        {
                            WritingId = 1,
                            WritingDescription = "denemeiçyazı1",
                            WritingName = "Deneme"
                        },
                        new
                        {
                            WritingId = 2,
                            WritingDescription = "denemeiçyazı2",
                            WritingName = "Deneme2"
                        },
                        new
                        {
                            WritingId = 3,
                            WritingDescription = "denemeiçyazı3",
                            WritingName = "Deneme3"
                        },
                        new
                        {
                            WritingId = 4,
                            WritingDescription = "denemeiçyazı4",
                            WritingName = "Deneme4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
